In [84]:
import numpy as np
import pandas as pd
import sys
import os
from IPython.display import Image

In [6]:
os.getcwd()

'c:\\source\\RCS_DA\\08'

In [7]:
os.listdir()

['08.ipynb']

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
np.array([1,2,3,'4'])

array(['1', '2', '3', '4'], dtype='<U11')

In [10]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
%%timeit
list(range(1000))

15.4 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%%timeit
np.arange(1000)

1.46 µs ± 160 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
scalar = np.array(21)

In [14]:
type(scalar)

numpy.ndarray

In [15]:
masivs = np.array([0,1,'string'])

masivs

array(['0', '1', 'string'], dtype='<U11')

In [16]:
masivs2 = np.array(['1', '2', 3], dtype='int')

masivs2

array([1, 2, 3])

In [17]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Viendimensja masīvs
masivs = np.array([1,2,3,4,54])

masivs[0]

1

In [19]:
masivs[4]

54

In [20]:
masivs.shape

(5,)

In [21]:
masivs.size

5

In [22]:
# Divdimensiju masīvs
mas1 = np.array([[1,2,3], [4,5,6]])
mas1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
mas1.shape

(2, 3)

In [24]:
mas1[1][2]

6

In [34]:
piem = np.array([[1,2,3], [4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [35]:
piem2 = np.array([[1,2,3], [4,5,6]])
piem2.shape

(2, 3)

In [36]:
piem2.size

6

In [37]:
piem2.ndim

2

In [38]:
piem4 = np.array(range(15))
piem4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
piem4.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
# Specialie masivi

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
# Vienibas matrica

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
piem5 = np.array([[1,2,3], [4,5,6]])
piem5

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
piem5[1,0]

4

In [ ]:
piem5[:,1]

array([2, 5])

In [ ]:
piem5[1,:]

array([4, 5, 6])

In [ ]:
piem6 = np.array([1,2,3,4,5,6,7,8,9,10])
piem6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
piem6[[True, False, True, False, True, False, True, False, True, False]]

NameError: name 'piem6' is not defined

In [ ]:
prece1 = [28,143,55]
prece2 = [12, 45, 90]
prece3 = [56, 67, 89]

w1,w2,w3 = 0.3, 0.4, 0.3

weights = [w1,w2,w3]

def vertibu_aprekinasana(prece, weights):
    return prece[0] * weights[0] + prece[1] * weights[1] + prece[2] * weights[2]

vertibu_aprekinasana(prece1,weights)

82.10000000000001

In [ ]:
list(zip(prece1, weights))

[(28, 0.3), (143, 0.4), (55, 0.3)]

In [ ]:
# v2

prece1 = [28,143,55]
prece2 = [12, 45, 90]
prece3 = [56, 67, 89]
w1,w2,w3 = 0.3, 0.4, 0.3
weights = [w1,w2,w3]

def vertibu_aprekins2(prece, weights):
    result = 0
    for p,w in zip(prece, weights):
        result += p*w
    return result

vertibu_aprekins2(prece1, weights)

82.10000000000001

In [28]:
# Izmantojot masivu

price1_ms = np.array(prece1)
print(price1_ms)
price2_ms = np.array(prece2)
print(price2_ms)
price3_ms = np.array(prece3)
print(price3_ms)


NameError: name 'prece1' is not defined

In [ ]:
weights_ms = np.array(weights)
weights_ms

array([0.3, 0.4, 0.3])

In [ ]:
np.dot(price1_ms, weights_ms)

82.10000000000001

In [ ]:
np.dot(price2_ms, weights_ms)

48.6

In [53]:
m1 = np.array([34,2,3])
m2 = np.array([4,5,6])

m1 >30




array([ True, False, False])

In [46]:
print(m1, m2)
m1 + m2

[34  2  3] [4 5 6]


array([38,  7,  9])

In [47]:
m3 = np.array([1,2])

m1 -m2


array([30, -3, -3])

In [48]:
m2-m3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
m1*m2

NameError: name 'm1' is not defined

In [ ]:
np.dot(m1, m2)


NameError: name 'np' is not defined

In [49]:
np.max(m1)

34

In [50]:
np.argmax(m1) # atgriz indeksu kur ir lielakais skaitlis


0

In [51]:
np.mean(m1) # masivu elementu videja vertiba

13.0

In [55]:
np.sum(m1)/m1.size

13.0

In [61]:
# masivu apvienosana
nullses_matr = np.zeros((2,3))

nullses_matr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
vieni_matr = np.ones((2,3))

vieni_matr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.vstack((nullses_matr, vieni_matr))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.hstack((nullses_matr,vieni_matr))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [64]:
np.concatenate((nullses_matr, vieni_matr), axis= 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.concatenate((nullses_matr,vieni_matr), axis= 1)


array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [68]:
# Transponet matricu

vieni_matr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.transpose(vieni_matr)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
masivs2 = np.array([[1,2,3,4,5,6], [3,4,5,6,7,5], [4,3,6,7,3,2]])
np.max(masivs2)

7

In [71]:
np.amax(masivs2)

7

In [72]:
np.amax(masivs2, axis=1)

array([6, 7, 7])

In [74]:
np.amax(masivs2, axis=0)

array([4, 4, 6, 7, 7, 6])

In [73]:
np.amin(masivs2, axis=1)

array([1, 3, 2])

In [80]:
np.amin(masivs2, axis = 0)

array([1, 2, 3, 4, 3, 2])

In [81]:
np.amin(masivs2, axis = 1)

array([1, 3, 2])

In [86]:
# Pandas

os.listdir()

data = pd.read_csv('customers.csv')

data

first_name last_name                               email  \
0       Joseph      Rice      josephrice131@slingacademy.com   
1         Gary     Moore       garymoore386@slingacademy.com   
2         John    Walker      johnwalker944@slingacademy.com   
3         Eric    Carter      ericcarter176@slingacademy.com   
4      William   Jackson  williamjackson427@slingacademy.com   
..         ...       ...                                 ...   
995     Alexis  Williams  alexiswilliams395@slingacademy.com   
996      Karen    Mendez     karenmendez129@slingacademy.com   
997   Michaela     Smith   michaelasmith815@slingacademy.com   
998   Kathleen     Scott   kathleenscott395@slingacademy.com   
999       Carl    Acosta      carlacosta740@slingacademy.com   

                    phone                                            address  \
0    +1-800-040-3135x6208             91773 Miller Shoal\nDiaztown, FL 38841   
1       221.945.4191x8872                6450 John Lodge\nTerriton, KY 95945   
2       388-142-4883x5370           27265 Murray Island\nKevinfort, PA 63231   
3           (451)259-5402                          USNS Knight\nFPO AA 76532   
4        625.626.9133x374            170 Jackson Loaf\nKristenland, AS 48876   
..                    ...                                                ...   
995    (659)856-5718x2171  76824 Richards Extensions Suite 123\nDenisevie...   
996            0339203729   48875 Brown Street\nEast Michelleburgh, KS 22960   
997  +1-106-147-6378x3133  576 Little Lights Suite 465\nSouth Johnny, PR ...   
998     (788)465-5647x419  5655 Gross Prairie Suite 656\nWest Jenniferbur...   
999   +1-183-389-0336x962                   Unit 2581 Box 3388\nDPO AA 71544   

     gender  age  registered  orders   spent          job  \
0      male   43  2019-05-05       7  568.29       Artist   
1      male   71  2020-05-20      11  568.92       Artist   
2      male   44  2020-04-04      11  497.12        Clerk   
3      male   38  2019-01-30      17  834.60      Butcher   
4      male   58  2022-07-01      14  151.59     Engineer   
..      ...  ...         ...     ...     ...          ...   
995  female   34  2019-07-16       4  351.18  Firefighter   
996  female   35  2020-01-30       2   45.27      Janitor   
997  female   23  2019-02-22       9  381.57         Chef   
998  female   72  2019-05-23       8  855.10        Clerk   
999    male   50  2020-01-27      20  456.16      Teacher   

                         hobbies  is_married  
0                 Playing sports       False  
1                       Swimming        True  
2                       Painting       False  
3    Playing musical instruments       False  
4                        Reading       False  
..                           ...         ...  
995                       Sewing       False  
996                       Baking       False  
997                      Drawing        True  
998                   Meditation        True  
999                       Hiking       False  

[1000 rows x 13 columns]

In [89]:
# Ignore headers
data = pd.read_csv('customers.csv', header = None)
data


0          1                                   2   \
0     first_name  last_name                               email   
1         Joseph       Rice      josephrice131@slingacademy.com   
2           Gary      Moore       garymoore386@slingacademy.com   
3           John     Walker      johnwalker944@slingacademy.com   
4           Eric     Carter      ericcarter176@slingacademy.com   
...          ...        ...                                 ...   
996       Alexis   Williams  alexiswilliams395@slingacademy.com   
997        Karen     Mendez     karenmendez129@slingacademy.com   
998     Michaela      Smith   michaelasmith815@slingacademy.com   
999     Kathleen      Scott   kathleenscott395@slingacademy.com   
1000        Carl     Acosta      carlacosta740@slingacademy.com   

                        3                                                  4   \
0                    phone                                            address   
1     +1-800-040-3135x6208             91773 Miller Shoal\nDiaztown, FL 38841   
2        221.945.4191x8872                6450 John Lodge\nTerriton, KY 95945   
3        388-142-4883x5370           27265 Murray Island\nKevinfort, PA 63231   
4            (451)259-5402                          USNS Knight\nFPO AA 76532   
...                    ...                                                ...   
996     (659)856-5718x2171  76824 Richards Extensions Suite 123\nDenisevie...   
997             0339203729   48875 Brown Street\nEast Michelleburgh, KS 22960   
998   +1-106-147-6378x3133  576 Little Lights Suite 465\nSouth Johnny, PR ...   
999      (788)465-5647x419  5655 Gross Prairie Suite 656\nWest Jenniferbur...   
1000   +1-183-389-0336x962                   Unit 2581 Box 3388\nDPO AA 71544   

          5    6           7       8       9            10  \
0     gender  age  registered  orders   spent          job   
1       male   43  2019-05-05       7  568.29       Artist   
2       male   71  2020-05-20      11  568.92       Artist   
3       male   44  2020-04-04      11  497.12        Clerk   
4       male   38  2019-01-30      17   834.6      Butcher   
...      ...  ...         ...     ...     ...          ...   
996   female   34  2019-07-16       4  351.18  Firefighter   
997   female   35  2020-01-30       2   45.27      Janitor   
998   female   23  2019-02-22       9  381.57         Chef   
999   female   72  2019-05-23       8   855.1        Clerk   
1000    male   50  2020-01-27      20  456.16      Teacher   

                               11          12  
0                         hobbies  is_married  
1                  Playing sports       False  
2                        Swimming        True  
3                        Painting       False  
4     Playing musical instruments       False  
...                           ...         ...  
996                        Sewing       False  
997                        Baking       False  
998                       Drawing        True  
999                    Meditation        True  
1000                       Hiking       False  

[1001 rows x 13 columns]

In [90]:
pd.read_csv('customers.csv', skiprows= 2)

Gary     Moore       garymoore386@slingacademy.com  \
0        John    Walker      johnwalker944@slingacademy.com   
1        Eric    Carter      ericcarter176@slingacademy.com   
2     William   Jackson  williamjackson427@slingacademy.com   
3      Nicole     Jones     nicolejones228@slingacademy.com   
4       David     Davis      daviddavis980@slingacademy.com   
..        ...       ...                                 ...   
993    Alexis  Williams  alexiswilliams395@slingacademy.com   
994     Karen    Mendez     karenmendez129@slingacademy.com   
995  Michaela     Smith   michaelasmith815@slingacademy.com   
996  Kathleen     Scott   kathleenscott395@slingacademy.com   
997      Carl    Acosta      carlacosta740@slingacademy.com   

        221.945.4191x8872                6450 John Lodge\nTerriton, KY 95945  \
0       388-142-4883x5370           27265 Murray Island\nKevinfort, PA 63231   
1           (451)259-5402                          USNS Knight\nFPO AA 76532   
2        625.626.9133x374            170 Jackson Loaf\nKristenland, AS 48876   
3              1783534757   14354 Baker Harbor Apt. 017\nEricville, HI 11192   
4        067.435.8553x692             021 Katherine Mall\nJameston, DC 24685   
..                    ...                                                ...   
993    (659)856-5718x2171  76824 Richards Extensions Suite 123\nDenisevie...   
994            0339203729   48875 Brown Street\nEast Michelleburgh, KS 22960   
995  +1-106-147-6378x3133  576 Little Lights Suite 465\nSouth Johnny, PR ...   
996     (788)465-5647x419  5655 Gross Prairie Suite 656\nWest Jenniferbur...   
997   +1-183-389-0336x962                   Unit 2581 Box 3388\nDPO AA 71544   

       male  71  2020-05-20  11  568.92       Artist  \
0      male  44  2020-04-04  11  497.12        Clerk   
1      male  38  2019-01-30  17  834.60      Butcher   
2      male  58  2022-07-01  14  151.59     Engineer   
3    female  33  2021-08-07  19   33.17   Unemployed   
4      male  59  2022-06-16   9  970.96       Doctor   
..      ...  ..         ...  ..     ...          ...   
993  female  34  2019-07-16   4  351.18  Firefighter   
994  female  35  2020-01-30   2   45.27      Janitor   
995  female  23  2019-02-22   9  381.57         Chef   
996  female  72  2019-05-23   8  855.10        Clerk   
997    male  50  2020-01-27  20  456.16      Teacher   

                        Swimming   True  
0                       Painting  False  
1    Playing musical instruments  False  
2                        Reading  False  
3                        Running   True  
4                 Playing sports  False  
..                           ...    ...  
993                       Sewing  False  
994                       Baking  False  
995                      Drawing   True  
996                   Meditation   True  
997                       Hiking  False  

[998 rows x 13 columns]

In [93]:
pd.read_csv('customers.csv', usecols=['gender', 'age'])

gender  age
0      male   43
1      male   71
2      male   44
3      male   38
4      male   58
..      ...  ...
995  female   34
996  female   35
997  female   23
998  female   72
999    male   50

[1000 rows x 2 columns]

In [94]:
pd.read_csv('customers.csv', index_col= ['first_name'])


last_name                               email  \
first_name                                                 
Joseph          Rice      josephrice131@slingacademy.com   
Gary           Moore       garymoore386@slingacademy.com   
John          Walker      johnwalker944@slingacademy.com   
Eric          Carter      ericcarter176@slingacademy.com   
William      Jackson  williamjackson427@slingacademy.com   
...              ...                                 ...   
Alexis      Williams  alexiswilliams395@slingacademy.com   
Karen         Mendez     karenmendez129@slingacademy.com   
Michaela       Smith   michaelasmith815@slingacademy.com   
Kathleen       Scott   kathleenscott395@slingacademy.com   
Carl          Acosta      carlacosta740@slingacademy.com   

                           phone  \
first_name                         
Joseph      +1-800-040-3135x6208   
Gary           221.945.4191x8872   
John           388-142-4883x5370   
Eric               (451)259-5402   
William         625.626.9133x374   
...                          ...   
Alexis        (659)856-5718x2171   
Karen                 0339203729   
Michaela    +1-106-147-6378x3133   
Kathleen       (788)465-5647x419   
Carl         +1-183-389-0336x962   

                                                      address  gender  age  \
first_name                                                                   
Joseph                 91773 Miller Shoal\nDiaztown, FL 38841    male   43   
Gary                      6450 John Lodge\nTerriton, KY 95945    male   71   
John                 27265 Murray Island\nKevinfort, PA 63231    male   44   
Eric                                USNS Knight\nFPO AA 76532    male   38   
William               170 Jackson Loaf\nKristenland, AS 48876    male   58   
...                                                       ...     ...  ...   
Alexis      76824 Richards Extensions Suite 123\nDenisevie...  female   34   
Karen        48875 Brown Street\nEast Michelleburgh, KS 22960  female   35   
Michaela    576 Little Lights Suite 465\nSouth Johnny, PR ...  female   23   
Kathleen    5655 Gross Prairie Suite 656\nWest Jenniferbur...  female   72   
Carl                         Unit 2581 Box 3388\nDPO AA 71544    male   50   

            registered  orders   spent          job  \
first_name                                            
Joseph      2019-05-05       7  568.29       Artist   
Gary        2020-05-20      11  568.92       Artist   
John        2020-04-04      11  497.12        Clerk   
Eric        2019-01-30      17  834.60      Butcher   
William     2022-07-01      14  151.59     Engineer   
...                ...     ...     ...          ...   
Alexis      2019-07-16       4  351.18  Firefighter   
Karen       2020-01-30       2   45.27      Janitor   
Michaela    2019-02-22       9  381.57         Chef   
Kathleen    2019-05-23       8  855.10        Clerk   
Carl        2020-01-27      20  456.16      Teacher   

                                hobbies  is_married  
first_name                                           
Joseph                   Playing sports       False  
Gary                           Swimming        True  
John                           Painting       False  
Eric        Playing musical instruments       False  
William                         Reading       False  
...                                 ...         ...  
Alexis                           Sewing       False  
Karen                            Baking       False  
Michaela                        Drawing        True  
Kathleen                     Meditation        True  
Carl                             Hiking       False  

[1000 rows x 12 columns]

In [ ]:
col_names = ['A', 'B', 'C', ]

In [97]:
# Failu lasisanas iespejas
file = open('customers.csv')

file.read()

'first_name,last_name,email,phone,address,gender,age,registered,orders,spent,job,hobbies,is_married\nJoseph,Rice,josephrice131@slingacademy.com,+1-800-040-3135x6208,"91773 Miller Shoal\nDiaztown, FL 38841",male,43,2019-05-05,7,568.29,Artist,Playing sports,False\nGary,Moore,garymoore386@slingacademy.com,221.945.4191x8872,"6450 John Lodge\nTerriton, KY 95945",male,71,2020-05-20,11,568.92,Artist,Swimming,True\nJohn,Walker,johnwalker944@slingacademy.com,388-142-4883x5370,"27265 Murray Island\nKevinfort, PA 63231",male,44,2020-04-04,11,497.12,Clerk,Painting,False\nEric,Carter,ericcarter176@slingacademy.com,(451)259-5402,"USNS Knight\nFPO AA 76532",male,38,2019-01-30,17,834.6,Butcher,Playing musical instruments,False\nWilliam,Jackson,williamjackson427@slingacademy.com,625.626.9133x374,"170 Jackson Loaf\nKristenland, AS 48876",male,58,2022-07-01,14,151.59,Engineer,Reading,False\nNicole,Jones,nicolejones228@slingacademy.com,1783534757,"14354 Baker Harbor Apt. 017\nEricville, HI 11192",female,3

In [98]:
file.seek(0)

0

In [140]:
file.read(2)

'bb'

In [142]:
file.readline()

'Joseph,Rice,josephrice131@slingacademy.com,+1-800-040-3135x6208,"91773 Miller Shoal\n'

In [143]:
file.seek(0)

for row in file:
    print(row)

first_name,last_name,email,phone,address,gender,age,registered,orders,spent,job,hobbies,is_married

Joseph,Rice,josephrice131@slingacademy.com,+1-800-040-3135x6208,"91773 Miller Shoal

Diaztown, FL 38841",male,43,2019-05-05,7,568.29,Artist,Playing sports,False

Gary,Moore,garymoore386@slingacademy.com,221.945.4191x8872,"6450 John Lodge

Territon, KY 95945",male,71,2020-05-20,11,568.92,Artist,Swimming,True

John,Walker,johnwalker944@slingacademy.com,388-142-4883x5370,"27265 Murray Island

Kevinfort, PA 63231",male,44,2020-04-04,11,497.12,Clerk,Painting,False

Eric,Carter,ericcarter176@slingacademy.com,(451)259-5402,"USNS Knight

FPO AA 76532",male,38,2019-01-30,17,834.6,Butcher,Playing musical instruments,False

William,Jackson,williamjackson427@slingacademy.com,625.626.9133x374,"170 Jackson Loaf

Kristenland, AS 48876",male,58,2022-07-01,14,151.59,Engineer,Reading,False

Nicole,Jones,nicolejones228@slingacademy.com,1783534757,"14354 Baker Harbor Apt. 017

Ericville, HI 11192",female,33

In [156]:
file = open('Test.txt', 'w')

os.listdir()

file.write('Riga Coding School')

file.close()


In [169]:
file = open('Test.txt', 'a')

file.write('dddddd\n')

7

In [192]:
with open('Test.txt') as file:
    print(file.read())

with open('Test.txt', 'a') as file:
    file.write('rrrrr')
    file.write('ddd\n')
    file.write('rrrr')

Riga Coding Schooldddddddddddddddddddddddddddddddddddd
dddddd
dddddd
dddddd
dddddd
dddddd
rrrrrdddrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd/nrrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrrrrrrrddd
rrrr


In [193]:
# Darbs ar excel failiem

import openpyxl


In [197]:
book = openpyxl.open('test.xlsx', read_only=True)

FileNotFoundError: [Errno 2] No such file or directory: 'test.xlsx'