In [1]:
import numpy as np
import sys
import os
from IPython.display import Image

In [2]:
os.getcwd()

'c:\\source\\RCS_DA\\08'

In [3]:
os.listdir()

['08.ipynb']

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([1,2,3,'4'])

array(['1', '2', '3', '4'], dtype='<U11')

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
%%timeit
list(range(1000))

71.9 µs ± 18.7 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%%timeit
np.arange(1000)

8.18 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
scalar = np.array(21)

In [11]:
type(scalar)

numpy.ndarray

In [13]:
masivs = np.array([0,1,'string'])

masivs

array(['0', '1', 'string'], dtype='<U11')

In [15]:
masivs2 = np.array(['1', '2', 3], dtype='int')

masivs2

array([1, 2, 3])